import type { Metadata } from "next";
import fonts from "@styles/fonts";
import "@styles/fonts.scss";
import "normalize.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={fonts}>{children}</body>
    </html>
  );
}
